### ISSUE TITLE
81-717 (СПБ): питерские плюшки

### ISSUE THREAD

**Issue by MrSandManFM** [metrostroi-repo/MetrostroiAddon#130]
Небольшие дополнения к вагону, которые часто (или всегда) есть в питере

Вещи, которые есть всегда или очень часто:

- [ ] 1. Клепки от бампера ПИПЕЦ СДЕЛАЙТЕ ЭТО УЖЕ ХТОНИБУДЬ, без них бампер очень пустой (#180)
![image](https://user-images.githubusercontent.com/4011223/107238197-9e363e80-6a38-11eb-91b5-a998622a0fb7.png)
- [ ] 2. Надписи на морде (номер вагона, приписка к ТЧ) (#180)
- [ ] 3. Шов под бампером (#180)
![image](https://user-images.githubusercontent.com/4011223/107238534-02f19900-6a39-11eb-9114-e8b3f34e69c9.png)
- [ ] 4. Волноводы эти. Конус вроде вместе с ПАшкой идет? @glebqip
![image](https://user-images.githubusercontent.com/4011223/107238638-23215800-6a39-11eb-9409-2360b481f836.png)
- [x] 5. Бегущая строка (#77)
- [ ] 6. Рамки в салоне со схемами и надоконные схемы
- [ ] 7. Длинные концевики (#182)
![image](https://user-images.githubusercontent.com/4011223/107239334-cf633e80-6a39-11eb-83bd-1a92654a967d.png)
- [ ] 8. LED красные лампы
![image](https://user-images.githubusercontent.com/4011223/107247782-b3b06600-6a42-11eb-8214-2b089d7362b3.png)

 

Вещи, которые можно сделать если у кого-то есть желание:
Возможно старый бампер для кастома (#78)
![image](https://user-images.githubusercontent.com/4011223/107238399-db023580-6a38-11eb-80c7-8c7285fcee1f.png)
Белые накладки:
![image](https://user-images.githubusercontent.com/4011223/107239242-b5296080-6a39-11eb-98d5-48fa2efa43d5.png)
